### ISSUE TITLE
text_inputs vs text_targets?

### ISSUE THREAD

**Issue by JRMeyer** [jxzhanggg/nonparaSeq2seqVC_code#16]
Hi @jxzhanggg,

What is the difference between `text_inputs` and `text_targets` here?

https://github.com/jxzhanggg/nonparaSeq2seqVC_code/blob/b9b22bb7e0a05afcc0dc538b74253de4414e119b/pre-train/reader/reader.py#L107

**Comment by jxzhanggg** [comment]
This is a history issue in my coding. This line should be deleted.
update in commit f7609595b7fc3a7705f04c12dba1d7d6f99d5939
