### ISSUE TITLE
deduce num_speakers from *list files

### ISSUE THREAD

**Issue by JRMeyer** [jxzhanggg/nonparaSeq2seqVC_code#18]
this should not be hard-coded:

https://github.com/jxzhanggg/nonparaSeq2seqVC_code/blob/b9b22bb7e0a05afcc0dc538b74253de4414e119b/pre-train/hparams.py#L33

and can easily be deduced from the `list.train` and `list.eval` files

**Comment by jxzhanggg** [comment]
Yes, I think the list.train / list eval could have a format like this:
speaker_id utterance_index
then the ``n_speakers'' can be calculated from list file.
n_speakers = get_n_speakers(listfile)
The mel path and text path could be obtain through a function like 
mel_path, text_path = get_path(speaker_id, utterance_index)
