### ISSUE TITLE
Documentation: Training Time

### ISSUE THREAD

**Issue by JRMeyer** [jxzhanggg/nonparaSeq2seqVC_code#20]
In the `README` there should be an estimate of training time. For example:

```
On 4 NVIDIA Titan GPUs, with a batch size of 32, pre-training on VCTK takes approximately 24 hours of wall-clock time. Fine-tuning on two speakers with this set-up takes approximately 2 hours of wall-clock time.
```

I made up those numbers, because I still haven't finished pre-training and fine-tuning. I have been pre-training for >15 hours on a `GeForce RTX 2080 Ti` with 12G of RAM, and I'm not sure when it's going to finish. I had to cut batchsize from 32 down to 16 to avoid OOM errors

**Comment by jxzhanggg** [comment]
That's my experiment training time:
On 1 NVIDIA 1080 Ti GPU, with a batch size of 32, pre-training on VCTK takes approximately 64 hours of wall-clock time. Fine-tuning on two speakers (500 utterances each speaker) with this set-up takes approximately 6 hours of wall-clock time.

**Comment by JRMeyer** [comment]
https://github.com/jxzhanggg/nonparaSeq2seqVC_code/pull/21

**Comment by JRMeyer** [comment]
0974551caac6791f2f9a2104c9735eb288d857fe
