### ISSUE TITLE
Alignment problem

### ISSUE THREAD

**Issue by Approximetal** [jxzhanggg/nonparaSeq2seqVC_code#23]
When I start training VCTK, it seems the alignment has something wrong. 
[step-28000-tts.pdf](https://github.com/jxzhanggg/nonparaSeq2seqVC_code/files/4057840/step-28000-tts.pdf)
[step-28000-vc.pdf](https://github.com/jxzhanggg/nonparaSeq2seqVC_code/files/4057842/step-28000-vc.pdf)
I met the same problem when training tacotron2, and the author suggested to use pre-train model. Does this code has pre-train model? Or any other mothod to deal with this problem?

**Comment by jxzhanggg** [comment]
I haven't meet this alignment collapse problem. My code does not inclue a pre-trained model currently. 
I suggest to exclude some long utterances in training data. Also, will the model recover
from this problem automatically if you keep training? If it will, I think you could still get normal results.

**Comment by Approximetal** [comment]
> I haven't meet this alignment collapse problem. My code does not inclue a pre-trained model currently.
> I suggest to exclude some long utterances in training data. Also, will the model recover
> from this problem automatically if you keep training? If it will, I think you could still get normal results.

It won't recover I suppose, it should be correct at the very begining, otherwise nothing gonna change. I'll try to use other datasets. Thank you!
