### ISSUE TITLE
Remove all Legacy Code

### ISSUE THREAD

**Issue by JRMeyer** [jxzhanggg/nonparaSeq2seqVC_code#24]
There is legacy code in different places, and this should all be removed

**Comment by JRMeyer** [comment]
one example: https://github.com/jxzhanggg/nonparaSeq2seqVC_code/blob/53c06cf1493f8e0e20702fe175beaaf26e2aa515/pre-train/inference.py#L109

**Comment by JRMeyer** [comment]
another example:
https://github.com/jxzhanggg/nonparaSeq2seqVC_code/blob/53c06cf1493f8e0e20702fe175beaaf26e2aa515/pre-train/hparams.py#L104

**Comment by jxzhanggg** [comment]
I've updated the code to solve this problem in cd000fe0021a82b841eccca576484035ba058186
