### ISSUE TITLE
Did you use a silence symbol?

### ISSUE THREAD

**Issue by youngsuenXMLY** [jxzhanggg/nonparaSeq2seqVC_code#31]
What do 'pau' and 'SOS/EOS' in symbol list mean? 'pau' means silence pause and 'SOS/EOS' means start or end of a sentence? How to use 'pau' and 'SOS/EOS'?

**Comment by jxzhanggg** [comment]
Hi, yes, 'SOS/EOS' means "start of sentence" and "end of sentence" and "pau" is silence pause.
It depends whether your  phoneme transcriptions contain those two labels.  The data preprocess code 
now won't generate "pau" or "SOS/EOS" token, so they're not used now.
