### ISSUE TITLE
list file format

### ISSUE THREAD

**Issue by leonardw86** [jxzhanggg/nonparaSeq2seqVC_code#33]
In the readme, you say, "Write a snippet of code to walk through the dataset for generating list file for train, valid and test set."  What is the format of the list file?  Can you post an example list file?

**Comment by jxzhanggg** [comment]
please see [here](https://github.com/jxzhanggg/nonparaSeq2seqVC_code/issues/2 )

**Comment by leonardw86** [comment]
Thank you!

-Wade
