### ISSUE TITLE
assignment statement of y_tts_pred & y_vc_pred

### ISSUE THREAD

**Issue by inconnu11** [jxzhanggg/nonparaSeq2seqVC_code#34]
Hi, when I have prepared everything to pre train,it raised an error saying"local variable 'y_tts' referenced before assignment ". So I add a statement before the loop 'for'. I set y_tts and y_tts_pred list type. But another error came " ValueError: not enough values to unpack(expected 12, got 0)". It referred to "y_pred".  
I think maybe there is a need to add an initialization statement of y_tts, y_vc and y_tts_pred, y_vc, y_tts_pred. Besides, is only one of y_tts_pred or y_vc_pred assigned at a time? It means the left is set None?

**Comment by jxzhanggg** [comment]
Hi, I suppose you don't prepare the validation data right, so the for loop never be runned. (you program actually don't go for validation). Please check again you validation data.

**Comment by inconnu11** [comment]
What's the right way to process validation data? I did the same preprocess operations on validation dataset as I did on training dataset.
The attached picture is the error reported when I directly run your code in pretrain/train.py
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/38338826/80471236-b9d2cb80-8975-11ea-9d6b-9e233c467371.png">

**Comment by inconnu11** [comment]
What's the right way to process validation data? I did the same preprocess operations on validation dataset as I did on training dataset.
The attached picture is the error reported when I directly run your code in pretrain/train.py
<img width="1288" alt="截屏2020-04-28 下午5 32 20" src="https://user-images.githubusercontent.com/38338826/80471762-7167dd80-8976-11ea-965d-a182c5ff8fec.png">

**Comment by inconnu11** [comment]
I retried running several days after my first try. And it works now. Magical and weird. Anyway, thanks for your reply!
