### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ChrisDelClea** [jxzhanggg/nonparaSeq2seqVC_code#44]
Hi Guys,

first of all, thanks for sharing this great research.
I have a question. Is it possible to offer a python "code" way to train / fine-tune the model?
For me personally, some examples how to do it would help a lot. 

Best regards 
Christian Klose

**Comment by KunZhou9646** [comment]
> Hi Guys,
> 
> first of all, thanks for sharing this great research. I have a question. Is it possible to offer a python "code" way to train / fine-tune the model? For me personally, some examples how to do it would help a lot.
> 
> Best regards Christian Klose

Hi Chris, I using this repo to achieve emotion style transfer with a strategy of pre-training/fine-tuning. And I publish one Interspeech 2021 paper on it. You can refer it through this link: https://arxiv.org/abs/2103.16809.

I also publish my codes on github. My codes are built upon this repo. :)

Regards,
Kun Zhou
